language: elixir
matrix:
  include:
    - elixir: "1.5.3"
      otp_release: "19.3"
    - elixir: "1.5.3"
      otp_release: "20.3"
    - elixir: "1.6.6"
      otp_release: "19.3"
    - elixir: "1.6.6"
      otp_release: "20.3"
    - elixir: "1.6.6"
      otp_release: "21.0"
    - elixir: "1.7.0-rc.1"
      otp_release: "20.3"
    - elixir: "1.7.0-rc.1"
      otp_release: "21.0"
    - elixir: "1.7.4"
      otp_release: "19.3"
    - elixir: "1.7.4"
      otp_release: "22.3"
    - elixir: "1.8.2"
      otp_release: "20.3"
    - elixir: "1.8.2"
      otp_release: "22.3"
    - elixir: "1.9.4"
      otp_release: "20.3"
    - elixir: "1.9.4"
      otp_release: "22.3"
    - elixir: "1.10.3"
      otp_release: "21.3"
    - elixir: "1.10.3"
      otp_release: "22.3"
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - jose.valim@gmail.com
    - lackac@lackac.hu
script:
  - elixir --version | grep -q '^Elixir 1\.5' || mix format --check-formatted
  - mix test
